# Generated by Django 3.2.7 on 2021-09-15 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
