# Generated by Django 3.2.7 on 2021-09-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
